### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by walegbenga** [alefduarte/laravel-react-hooks-redux-boilerplate#8]
After following the tutorial, I couldn't get it to work. I believe the problem is with Laravel but it isn't displaying any error.

**Comment by alefduarte** [comment]
I just tried it out again and it worked pretty fine. Make sure your .env file and your database connection are correct. If you think the problem is Laravel and it is not displaying any error, check /storage/logs/ there will be a file like `laravel-2020-06-30.log` which might contain the error. Also, make sure you ran `php artisan key:generate` to generate the required APP_KEY.

**Comment by walegbenga** [comment]
Nothing special in the error log. I have generated APP_KEY, the tables are created in the db(So the database connection are correct).
But I don't start the server(I mean my apache server as I don't use Homestead and XAMPP) as I thought the `php artisan serve` will start the server.

Do I really need to start the server?

**Comment by alefduarte** [comment]
You must use `php artisan serve`, you might set the ip and port if you want, but it will by default set them to 127.0.0.1:8000
`php artisan serve --host=127.0.0.1 --port=8000`

Check this out (https://www.hostinger.com/tutorials/how-to-install-laravel-on-ubuntu-18-04-with-apache-and-php/) to learn about some changes you might have to make to deploy it and use with Apache.
You might want to skip to "Using Laravel for Local Development" since you have already cloned this repo and made the required steps.
